name: auto-build

on:
  push:
    branches:
      - "*"

permissions:
  contents: write

env:
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Tag
        id: create_tag
        run: |
          echo "TAG_NAME=$(git show -s --format=%B HEAD | sed 's/[ \/]*//g')" >> $GITHUB_ENV
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git tag $(git show -s --format=%B HEAD | sed 's/[ \/]*//g')
          # git push origin $(git show -s --format=%B HEAD | sed 's/[ \/]*//g')

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull Arch Linux Docker image
        run: docker pull archlinux:latest

      - name: Building package
        run: |
          docker run --rm \
            -v $(pwd):/workspace -w /workspace archlinux:latest bash -c "
              echo 'Building Arch Linux package';
              pacman -Syu --noconfirm;
              pacman -S base-devel git sudo --noconfirm;

              # Create a non-root user
              useradd -m builder;
              echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers;

              # Ensure builder user has ownership of the workspace
              chown -R builder /workspace;

              # Switch to the non-root user
              sudo -u builder bash -c '
                git config --global --add safe.directory /workspace;
                makepkg -s --noconfirm;
              '
            "

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          body: Workflow Hash ```${{ github.sha }}```
          files: |
            *.pkg.tar.zst
